#!/bin/bash
KEY=.vagrant/machines/default/virtualbox/private_key
scp -P 2222 -i ${KEY} vagrant@localhost:~/.minikube/client.crt ~/.kube/client.crt
scp -P 2222 -i ${KEY} vagrant@localhost:~/.minikube/client.key ~/.kube/client.key
scp -P 2222 -i ${KEY} vagrant@localhost:~/.minikube/ca.crt ~/.kube/ca.crt
